### ISSUE TITLE
Raspberry Pi 3B "cannot execute binary file: Exec format error"

### ISSUE THREAD

**Issue by Qerlak** [ianmarmour/nvidia-clerk#124]
Operating system: Raspberry Pi 3B running latest Raspbian 8.0 firmware
Version of nvidia-clerk you're running: Latest release with linux ARM support
Parameters passed in (redact sensitive info): see image below (redacted api link for obvious reasons)
Additional info: Tried both the 32bit and 64 bit options posted on the releases tab, both aren't loading.

![2020-09-26-165536_1920x1080_scrot (2)](https://user-images.githubusercontent.com/67479710/94346146-b90f9580-fff8-11ea-986c-fb0ef506bd7b.png)

(scrot is the command to capture the screenshot)
Thx for the help and the awesome tool,
-Qerlak

**Comment by reubenprevost** [comment]
I don't have a rPi to test this, but it seems like you have some knowledge on navigating your terminal.

It might help if you download the source and build the executable for yourself. It's not difficult, you just need to download golang.

If Ian has a rpi, I'm sure he would be able to help.

**Comment by Qerlak** [comment]
Yeah I'm taking a CLI based course at Uni using this Pi, I have the files in the home folder so they are in the same directory. I'll look into building the exec myself, thanks for the help.

**Comment by MadEngineer75** [comment]
The arm executable provided is also not able to be executed on my Pi 4. Upon investigation I found out the the Go compiler supports different version of the arm architecture(v5, v6, and v7). To specify the arm version to build for you just add GOARM=(5, 6, or 7) to the build variables.

Weirdly enough my Raspberry Pi works with all arm versions when I specify a specific arm version to build for on my Windows machine. But, when I don't specify an arm version my Pi doesn't want to execute the binary.

So I suggest a build for arm v5, since it seems to work on newer arm architectures, if Ian don't want to build for every arm version.

**Comment by ianmarmour** [comment]
I'll just build for all the arm architectures it's been a while since I've built anything on arm I forgot there's different versions as well 32 vs 64.

**Comment by ianmarmour** [comment]
added v5 as the latest release because I'm lazy for now, going to resolve this feel free to re-open if it occurs again.

**Comment by MadEngineer75** [comment]
My Pi still can't run any of the binaries provided and I tried different versions. I honestly don't know the problem, my Windows machine compiles working binaries for the Pi using an identical build command.

**Comment by Qerlak** [comment]
Yeah. at this point I'm just using my low powered ultrabook to do the checking and then send a discord link to my discord channel I have set up.
