### ISSUE TITLE
All notification methods broken when region is GBR(maybe others) - testing with 2060

### ISSUE THREAD

**Issue by C0pyP4sta** [ianmarmour/nvidia-clerk#158]
As discussed in Discord and confirmed by redstone2019:

**To Reproduce**
Running: .\nvidia-clerk-windows.exe -desktop -discord -sms -region=GBR -model=2060
... produces NO Win10 notification, no discord bot activity nor an SMS, as expected. (All variables are SET correctly)

Running: .\nvidia-clerk-windows.exe -desktop -discord -sms -region=USA -model=2060
... results in success with all 3 notifications received. Only change is region.

Both commands execute correctly and show the same console output with "PRODUCT_INVENTORY_IN_STOCK" when polling etc.
There is a separate (known) issue with the item not added to cart, due to store/checkout changes.

This bug suggests that the region GBR - maybe others not USA - are not working correctly in the code?

Suggested this may be down to 2060, due to regional naming differences - but note that the polling DOES work, just notifications are broken.
Concern / unsure now, if all notifications for ALLproducts (namely 3080/3090!!!) may be affected, for anyone outside of the USA...

**Expected behavior**
Any region should produce notifications using various channels, regardless of region and/or product.

**Screenshots**
![image](https://user-images.githubusercontent.com/72164472/94731149-353d0c80-035c-11eb-986f-369b0f564194.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1903
 - Version: 3.7.9 *latest*

**Additional context**
Behaviour confirmed by others, toggling region with the in-stock 2060.

**Comment by Hosua101** [comment]
Checkout is not working for USA region either.
Only difference is that I don't get an error that it can't add to checkout.
It just shows that it is in stock and bot stops.
I have Chrome running but no new tab is created for it or anything.
I do however receive the notification from SMS, Discord and Desktop notifications.

**Comment by Bungusbeefcake** [comment]
When using the -remote option, it would normally send me the full URL, i.e. https://store.nvidia.com/store?Action=DisplayHGOP2LandingPage&Locale=en_US&SiteID=nvidia&Token=WVE6V1NTKCMLOnVwfQYDcXRiAgEIBWlhYmV9d38OAHFUdwA%3D&session=651C9C346CD39EC5D3D0F56C2FF26D055A255C87B32BAB672C79E30C003AD5942CE557DA02C99B0EB84CFB84762D5C4DF9941C201BA2DBAD670DEA378A54A459A56AA43A15010CECE99C7FAC96D478C2&=1601239976

However, this time the response in that section is "&=1601501621". Unsure what that means. But otherwise it's the same, not opening in Chrome, and on the USA region, doesn't give the error.

**Comment by redstone2019** [comment]
![image](https://user-images.githubusercontent.com/50508889/94853308-0ff1e200-03e0-11eb-881f-4e2ecfb60dc8.png)
Desktop notifications work for GBR in v3.82 and also go to #162 for wrong page stuff, thanks guys.
