### ISSUE TITLE
Testing with 2060 but does not add to cart

### ISSUE THREAD

**Issue by Getyourcardnow** [ianmarmour/nvidia-clerk#164]
I tried the test by modding the line
nvidia-clerk-windows.exe -region=USA -model=2060

When I run it, it opens the browser but does not add to cart. I see there are no 2060's available. I'm just hoping the script will work. When running
nvidia-clerk-windows.exe -region=USA -model=3090  it does keep going in the CMD line as out of stock so I would say it is working as intended? I just want to ensure it adds to cart thats all.

**Comment by kucky1207** [comment]
i just tried as well same problem even tough it is in stock
Downloads\nvidia-clerk-windows.exe -region=CZE -model=2060

opens nvidia site but not on 2060 page or any store page, but rather on homepage and nothing in cart. all other cards are out of stock so cant test any other in my region

it opens this 
https://www.nvidia.com/en-gb/geforce/20-series/

just sold my 1080ti gotta get that 3070 asap otherwise ill be looking at youtube for a long time :D

**Comment by redstone2019** [comment]
closing in favor of #162
